### 1) Write a python code that ask the user to enter his birth year and then print his age in years.

In [1]:
from datetime import date

In [2]:
date.today().year

2021

In [3]:
birth_year = int(input())
age = date.today().year - birth_year
print(f"you are {age} years old")

1997
you are 24 years old


### 2) Write a python code to find Sum and Average of N Natural Numbers

In [4]:
num = int(input())
Sum = sum(range(num+1))
avg = Sum/num
print(f"the sum of natural numbers from 1 to {num} is {Sum}")
print(f"the average of natural numbers from 1 to {num} is {avg}")

50
the sum of natural numbers from 1 to 50 is 1275
the average of natural numbers from 1 to 50 is 25.5


### 3) Pyramid Pattern with Stars

In [24]:
num = int(input())
i = 0
while i<num:
    print((num-i)*" "+(2*i+1)*"*")
    i += 1

10
          *
         ***
        *****
       *******
      *********
     ***********
    *************
   ***************
  *****************
 *******************


### 4) Python Program to Check Even or Odd

In [6]:
num = int(input())
if num%2 == 0:
    print(f"{num} is an even number")
else:
    print(f"{num} is an odd number")

3
3 is an odd number


### 5) Remove Vowels from String

In [7]:
string = input()
s = ''
for c in string:
    if c.lower() not in ['a','e','i','o','u']:
        s = s+c
print(s)

MoAz
Mz


### 6)Write a Python program to write a list to a file.

In [8]:
with open("test.txt","a") as file:
    file.write(input()+'\n')

[5,6]


### 7)Write a Python function to sum all the numbers in a list

In [9]:
def sum_list(l):
    return sum(l)
print(sum_list([1,2,3,4,5]))

15


### 8) Write a Python program to print the even numbers from a given list.

In [10]:
def even_nums(nums):
    for num in nums:
        if num%2 != 0:
            nums.remove(num)
    return nums
print(even_nums([1,2,3,4,5]))

[2, 4]


### 9)Write a Python class which has two methods get_String and print_String. get_String accept a string from the user and print_String print the string in upper case.

In [11]:
class string:
    def __init__(self,s):
        self.s = s
    def get_string(self):
        print(self.s)
    def print_string(self):
        print(self.s.upper())

In [12]:
s = string('MoAz')

In [13]:
s.get_string()
s.print_string()

MoAz
MOAZ


### 10) Write a python class to calculate the average speed, distance travelled and the trip duration of a vehicle: car, bus, train, bike, motorcycle, plane etc. constructed by a Distance (Km) and Time(H) and a method which will compute the speed of a car.

In [14]:
class vehicle:
    def __init__(self,dist,time):
        self.dist = dist
        self.time = time
    def speed(self):
        return self.dist/self.time

car = vehicle(60,1)
print(car.dist,car.time,car.speed())

60 1 60.0


### 11) Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [15]:
import numpy as np

In [16]:
print(np.array(range(2,10+1)).reshape(3,3))

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


### 12) Write a NumPy program to remove the negative values in a NumPy array with 0

In [17]:
np.array([-1,-2,-3,-4,0,1,2,3,4])*(np.array([-1,-2,-3,-4,0,1,2,3,4]) >= 0).astype(int)

array([0, 0, 0, 0, 0, 1, 2, 3, 4])

### 13) Write a NumPy program to partition a given array in a specified position and move all the smaller elements values to the left of the partition, and the remaining values to the right, in arbitrary order.

In [18]:
np.partition([70,50,20,30,-11,60,50,40],4)

array([-11,  30,  20,  40,  50,  50,  60,  70])

### 14) Write a program that repeatedly prompts a user for integer numbers until the user enters 'done'. Once 'done' is entered, print out the largest and smallest of the numbers. If the user enters anything other than a valid number catch it with a try/except and put out an appropriate message and ignore the number. Enter 7, 2, bob, 10, and 4 and match the output below.

In [19]:
nums = []
while True:
    user_input = input()
    try:
        if int(user_input):
            nums.append(int(user_input))
    except Exception as e:
        if user_input == 'done':
            print(max(nums))
            print(min(nums))
            print(nums)
            break
        else:
            print('Invalid input')
        
        

7
2
bob
Invalid input
10
4
done
10
2
[7, 2, 10, 4]


### 15) Write a program that prompts for a file name, then opens that file and reads through the file, and print the contents of the file in upper case. Use the file words.txt to produce the output below.

In [20]:
with open("abc.txt","r") as file:
    for line in file:
        print(line.upper())

RED

GREEN

WHITE

BLACK

PINK

YELLOW



### 16) Open the file mbox-short.txt and read it line by line. When you find a line that starts with 'From ' like the following line:
#### From stephen.marquard@uct.ac.za Sat Jan 5 09:14:16 2008 You will parse the From line using split() and print out the second word in the line (i.e. the entire address of the person who sent the message). Then print out a count at the end. Hint: make sure not to include the lines that start with 'From:'.

In [30]:
with open("mbox-short.txt","r") as file:
    i = 1
    for line in file:
        try:
            if line.split()[0]=="From":
                #print(line.split())
                print("".join(line.split()[1:2]))#print('OK')
                i+=1
        except Exception as e:
            continue
    print(f"we have {i} lines")

stephen.marquard@uct.ac.za
louis@media.berkeley.edu
zqian@umich.edu
rjlowe@iupui.edu
zqian@umich.edu
rjlowe@iupui.edu
cwen@iupui.edu
cwen@iupui.edu
gsilver@umich.edu
gsilver@umich.edu
zqian@umich.edu
gsilver@umich.edu
wagnermr@iupui.edu
zqian@umich.edu
antranig@caret.cam.ac.uk
gopal.ramasammycook@gmail.com
david.horwitz@uct.ac.za
david.horwitz@uct.ac.za
david.horwitz@uct.ac.za
david.horwitz@uct.ac.za
stephen.marquard@uct.ac.za
louis@media.berkeley.edu
louis@media.berkeley.edu
ray@media.berkeley.edu
cwen@iupui.edu
cwen@iupui.edu
cwen@iupui.edu
we have 28 lines
